-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity softmax_latency_ap_fixed_ap_fixed_softmax_config13_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of softmax_latency_ap_fixed_ap_fixed_softmax_config13_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv18_1FFFF : STD_LOGIC_VECTOR (17 downto 0) := "011111111111111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exp_table1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce0 : STD_LOGIC;
    signal exp_table1_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce1 : STD_LOGIC;
    signal exp_table1_q1 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce2 : STD_LOGIC;
    signal exp_table1_q2 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce3 : STD_LOGIC;
    signal exp_table1_q3 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce4 : STD_LOGIC;
    signal exp_table1_q4 : STD_LOGIC_VECTOR (16 downto 0);
    signal invert_table2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table2_ce0 : STD_LOGIC;
    signal invert_table2_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal y_V_4_reg_514 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_res_0_V_reg_519 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_0_V_reg_519_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_0_V_reg_519_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_0_V_reg_519_pp0_iter4_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_reg_526 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_reg_526_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_reg_526_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_reg_526_pp0_iter4_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_reg_533 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_reg_533_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_reg_533_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_reg_533_pp0_iter4_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_reg_540 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_reg_540_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_reg_540_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_reg_540_pp0_iter4_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_4_V_reg_552 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_4_V_reg_552_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_4_V_reg_552_pp0_iter4_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_8_fu_306_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_8_reg_558 : STD_LOGIC_VECTOR (17 downto 0);
    signal inv_exp_sum_V_reg_569 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1116_fu_366_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln251_fu_170_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_1_fu_185_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_2_fu_200_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_3_fu_215_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_4_fu_230_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln259_fu_361_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_V_fu_160_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_1_fu_175_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_2_fu_190_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_3_fu_205_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln203_1_fu_237_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln203_fu_234_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_2_fu_246_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_s_fu_256_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln746_fu_252_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_6_fu_264_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln203_3_fu_243_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln203_2_fu_240_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_fu_276_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_10_fu_286_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln746_1_fu_282_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_7_fu_294_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln746_1_fu_302_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln746_fu_272_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_11_fu_315_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_9_fu_322_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln203_4_fu_312_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_11_fu_329_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_12_fu_335_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_343_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_5_fu_353_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_459_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_466_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_473_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_480_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_487_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_459_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_459_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_466_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_466_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_473_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_473_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_480_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_480_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_487_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_487_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_459_ce : STD_LOGIC;
    signal grp_fu_466_ce : STD_LOGIC;
    signal grp_fu_473_ce : STD_LOGIC;
    signal grp_fu_480_ce : STD_LOGIC;
    signal grp_fu_487_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to6 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_459_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_466_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_473_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_480_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_487_p00 : STD_LOGIC_VECTOR (25 downto 0);

    component myproject_mul_mul_17ns_18s_26_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component softmax_latency_ap_fixed_ap_fixed_softmax_config13_s_exp_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component softmax_latency_ap_fixed_ap_fixed_softmax_config13_s_invecud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table1_U : component softmax_latency_ap_fixed_ap_fixed_softmax_config13_s_exp_bkb
    generic map (
        DataWidth => 17,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table1_address0,
        ce0 => exp_table1_ce0,
        q0 => exp_table1_q0,
        address1 => exp_table1_address1,
        ce1 => exp_table1_ce1,
        q1 => exp_table1_q1,
        address2 => exp_table1_address2,
        ce2 => exp_table1_ce2,
        q2 => exp_table1_q2,
        address3 => exp_table1_address3,
        ce3 => exp_table1_ce3,
        q3 => exp_table1_q3,
        address4 => exp_table1_address4,
        ce4 => exp_table1_ce4,
        q4 => exp_table1_q4);

    invert_table2_U : component softmax_latency_ap_fixed_ap_fixed_softmax_config13_s_invecud
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table2_address0,
        ce0 => invert_table2_ce0,
        q0 => invert_table2_q0);

    myproject_mul_mul_17ns_18s_26_3_1_U3091 : component myproject_mul_mul_17ns_18s_26_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_459_p0,
        din1 => grp_fu_459_p1,
        ce => grp_fu_459_ce,
        dout => grp_fu_459_p2);

    myproject_mul_mul_17ns_18s_26_3_1_U3092 : component myproject_mul_mul_17ns_18s_26_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_466_p0,
        din1 => grp_fu_466_p1,
        ce => grp_fu_466_ce,
        dout => grp_fu_466_p2);

    myproject_mul_mul_17ns_18s_26_3_1_U3093 : component myproject_mul_mul_17ns_18s_26_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_473_p0,
        din1 => grp_fu_473_p1,
        ce => grp_fu_473_ce,
        dout => grp_fu_473_p2);

    myproject_mul_mul_17ns_18s_26_3_1_U3094 : component myproject_mul_mul_17ns_18s_26_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_480_p0,
        din1 => grp_fu_480_p1,
        ce => grp_fu_480_ce,
        dout => grp_fu_480_p2);

    myproject_mul_mul_17ns_18s_26_3_1_U3095 : component myproject_mul_mul_17ns_18s_26_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_487_p0,
        din1 => grp_fu_487_p1,
        ce => grp_fu_487_ce,
        dout => grp_fu_487_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                exp_res_0_V_reg_519 <= exp_table1_q0;
                exp_res_1_V_reg_526 <= exp_table1_q1;
                exp_res_2_V_reg_533 <= exp_table1_q2;
                exp_res_3_V_reg_540 <= exp_table1_q3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exp_res_0_V_reg_519_pp0_iter2_reg <= exp_res_0_V_reg_519;
                exp_res_0_V_reg_519_pp0_iter3_reg <= exp_res_0_V_reg_519_pp0_iter2_reg;
                exp_res_0_V_reg_519_pp0_iter4_reg <= exp_res_0_V_reg_519_pp0_iter3_reg;
                exp_res_1_V_reg_526_pp0_iter2_reg <= exp_res_1_V_reg_526;
                exp_res_1_V_reg_526_pp0_iter3_reg <= exp_res_1_V_reg_526_pp0_iter2_reg;
                exp_res_1_V_reg_526_pp0_iter4_reg <= exp_res_1_V_reg_526_pp0_iter3_reg;
                exp_res_2_V_reg_533_pp0_iter2_reg <= exp_res_2_V_reg_533;
                exp_res_2_V_reg_533_pp0_iter3_reg <= exp_res_2_V_reg_533_pp0_iter2_reg;
                exp_res_2_V_reg_533_pp0_iter4_reg <= exp_res_2_V_reg_533_pp0_iter3_reg;
                exp_res_3_V_reg_540_pp0_iter2_reg <= exp_res_3_V_reg_540;
                exp_res_3_V_reg_540_pp0_iter3_reg <= exp_res_3_V_reg_540_pp0_iter2_reg;
                exp_res_3_V_reg_540_pp0_iter4_reg <= exp_res_3_V_reg_540_pp0_iter3_reg;
                exp_res_4_V_reg_552_pp0_iter3_reg <= exp_res_4_V_reg_552;
                exp_res_4_V_reg_552_pp0_iter4_reg <= exp_res_4_V_reg_552_pp0_iter3_reg;
                inv_exp_sum_V_reg_569 <= invert_table2_q0;
                p_Val2_8_reg_558 <= p_Val2_8_fu_306_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                exp_res_4_V_reg_552 <= exp_table1_q4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                y_V_4_reg_514 <= data_4_V_read(15 downto 6);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln746_1_fu_282_p2 <= std_logic_vector(unsigned(exp_res_2_V_reg_533) + unsigned(exp_res_3_V_reg_540));
    add_ln746_fu_252_p2 <= std_logic_vector(unsigned(exp_res_0_V_reg_519) + unsigned(exp_res_1_V_reg_526));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to6_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to6 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to6)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to6 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= grp_fu_459_p2(25 downto 10);
    ap_return_1 <= grp_fu_466_p2(25 downto 10);
    ap_return_2 <= grp_fu_473_p2(25 downto 10);
    ap_return_3 <= grp_fu_480_p2(25 downto 10);
    ap_return_4 <= grp_fu_487_p2(25 downto 10);
    exp_table1_address0 <= zext_ln251_fu_170_p1(10 - 1 downto 0);
    exp_table1_address1 <= zext_ln251_1_fu_185_p1(10 - 1 downto 0);
    exp_table1_address2 <= zext_ln251_2_fu_200_p1(10 - 1 downto 0);
    exp_table1_address3 <= zext_ln251_3_fu_215_p1(10 - 1 downto 0);
    exp_table1_address4 <= zext_ln251_4_fu_230_p1(10 - 1 downto 0);

    exp_table1_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce0 <= ap_const_logic_1;
        else 
            exp_table1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce1_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce1 <= ap_const_logic_1;
        else 
            exp_table1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce2_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce2 <= ap_const_logic_1;
        else 
            exp_table1_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce3_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce3 <= ap_const_logic_1;
        else 
            exp_table1_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce4 <= ap_const_logic_1;
        else 
            exp_table1_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_459_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_459_ce <= ap_const_logic_1;
        else 
            grp_fu_459_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_459_p0 <= grp_fu_459_p00(17 - 1 downto 0);
    grp_fu_459_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_0_V_reg_519_pp0_iter4_reg),26));
    grp_fu_459_p1 <= sext_ln1116_fu_366_p1(18 - 1 downto 0);

    grp_fu_466_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_466_ce <= ap_const_logic_1;
        else 
            grp_fu_466_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_466_p0 <= grp_fu_466_p00(17 - 1 downto 0);
    grp_fu_466_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_1_V_reg_526_pp0_iter4_reg),26));
    grp_fu_466_p1 <= sext_ln1116_fu_366_p1(18 - 1 downto 0);

    grp_fu_473_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_473_ce <= ap_const_logic_1;
        else 
            grp_fu_473_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_473_p0 <= grp_fu_473_p00(17 - 1 downto 0);
    grp_fu_473_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_2_V_reg_533_pp0_iter4_reg),26));
    grp_fu_473_p1 <= sext_ln1116_fu_366_p1(18 - 1 downto 0);

    grp_fu_480_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_480_ce <= ap_const_logic_1;
        else 
            grp_fu_480_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_480_p0 <= grp_fu_480_p00(17 - 1 downto 0);
    grp_fu_480_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_3_V_reg_540_pp0_iter4_reg),26));
    grp_fu_480_p1 <= sext_ln1116_fu_366_p1(18 - 1 downto 0);

    grp_fu_487_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_487_ce <= ap_const_logic_1;
        else 
            grp_fu_487_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_487_p0 <= grp_fu_487_p00(17 - 1 downto 0);
    grp_fu_487_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_4_V_reg_552_pp0_iter4_reg),26));
    grp_fu_487_p1 <= sext_ln1116_fu_366_p1(18 - 1 downto 0);
    invert_table2_address0 <= zext_ln259_fu_361_p1(10 - 1 downto 0);

    invert_table2_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            invert_table2_ce0 <= ap_const_logic_1;
        else 
            invert_table2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_10_fu_286_p3 <= p_Val2_5_fu_276_p2(17 downto 17);
    p_Result_11_fu_315_p3 <= p_Val2_8_reg_558(17 downto 17);
    p_Result_12_fu_335_p3 <= p_Val2_11_fu_329_p2(17 downto 17);
    p_Result_s_fu_256_p3 <= p_Val2_2_fu_246_p2(17 downto 17);
    p_Val2_11_fu_329_p2 <= std_logic_vector(unsigned(p_Val2_9_fu_322_p3) + unsigned(zext_ln203_4_fu_312_p1));
    p_Val2_2_fu_246_p2 <= std_logic_vector(unsigned(zext_ln203_1_fu_237_p1) + unsigned(zext_ln203_fu_234_p1));
    p_Val2_5_fu_276_p2 <= std_logic_vector(unsigned(zext_ln203_3_fu_243_p1) + unsigned(zext_ln203_2_fu_240_p1));
    p_Val2_6_fu_264_p3 <= 
        ap_const_lv17_1FFFF when (p_Result_s_fu_256_p3(0) = '1') else 
        add_ln746_fu_252_p2;
    p_Val2_7_fu_294_p3 <= 
        ap_const_lv17_1FFFF when (p_Result_10_fu_286_p3(0) = '1') else 
        add_ln746_1_fu_282_p2;
    p_Val2_8_fu_306_p2 <= std_logic_vector(unsigned(zext_ln746_1_fu_302_p1) + unsigned(zext_ln746_fu_272_p1));
    p_Val2_9_fu_322_p3 <= 
        ap_const_lv18_1FFFF when (p_Result_11_fu_315_p3(0) = '1') else 
        p_Val2_8_reg_558;
        sext_ln1116_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inv_exp_sum_V_reg_569),26));

    tmp_fu_343_p4 <= p_Val2_11_fu_329_p2(17 downto 8);
    y_V_1_fu_175_p4 <= data_1_V_read(15 downto 6);
    y_V_2_fu_190_p4 <= data_2_V_read(15 downto 6);
    y_V_3_fu_205_p4 <= data_3_V_read(15 downto 6);
    y_V_5_fu_353_p3 <= 
        ap_const_lv10_1FF when (p_Result_12_fu_335_p3(0) = '1') else 
        tmp_fu_343_p4;
    y_V_fu_160_p4 <= data_0_V_read(15 downto 6);
    zext_ln203_1_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_1_V_reg_526),18));
    zext_ln203_2_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_2_V_reg_533),18));
    zext_ln203_3_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_3_V_reg_540),18));
    zext_ln203_4_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_4_V_reg_552),18));
    zext_ln203_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_0_V_reg_519),18));
    zext_ln251_1_fu_185_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_1_fu_175_p4),64));
    zext_ln251_2_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_2_fu_190_p4),64));
    zext_ln251_3_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_3_fu_205_p4),64));
    zext_ln251_4_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_4_reg_514),64));
    zext_ln251_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_fu_160_p4),64));
    zext_ln259_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_5_fu_353_p3),64));
    zext_ln746_1_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_7_fu_294_p3),18));
    zext_ln746_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_6_fu_264_p3),18));
end behav;
