// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_fixed_ap_fixed_config11_0_0_0_0_0_0 (
        ap_ready,
        data_0_V_read,
        data_2_V_read,
        data_3_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_12_V_read,
        data_14_V_read,
        data_15_V_read,
        data_17_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);


output   ap_ready;
input  [6:0] data_0_V_read;
input  [6:0] data_2_V_read;
input  [6:0] data_3_V_read;
input  [6:0] data_5_V_read;
input  [6:0] data_6_V_read;
input  [6:0] data_7_V_read;
input  [6:0] data_8_V_read;
input  [6:0] data_9_V_read;
input  [6:0] data_10_V_read;
input  [6:0] data_12_V_read;
input  [6:0] data_14_V_read;
input  [6:0] data_15_V_read;
input  [6:0] data_17_V_read;
input  [6:0] data_19_V_read;
input  [6:0] data_20_V_read;
input  [6:0] data_21_V_read;
input  [6:0] data_24_V_read;
input  [6:0] data_25_V_read;
input  [6:0] data_26_V_read;
input  [6:0] data_27_V_read;
input  [6:0] data_28_V_read;
input  [6:0] data_29_V_read;
input  [6:0] data_31_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;

wire  signed [6:0] mul_ln1118_8_fu_278_p0;
wire  signed [13:0] sext_ln1116_15_fu_3309_p1;
wire  signed [6:0] mul_ln1118_3_fu_283_p0;
wire  signed [6:0] mul_ln1118_10_fu_284_p0;
wire  signed [13:0] sext_ln1116_17_fu_3387_p1;
wire  signed [6:0] mul_ln1118_2_fu_285_p0;
wire  signed [6:0] mul_ln1118_fu_291_p0;
wire  signed [6:0] mul_ln1118_9_fu_296_p0;
wire  signed [6:0] mul_ln1118_1_fu_303_p0;
wire  signed [6:0] mul_ln1118_4_fu_310_p0;
wire  signed [13:0] sext_ln1116_5_fu_2888_p1;
wire  signed [6:0] mul_ln1118_7_fu_311_p0;
wire  signed [6:0] mul_ln1118_6_fu_313_p0;
wire  signed [6:0] mul_ln1118_5_fu_315_p0;
wire   [12:0] shl_ln_fu_2156_p3;
wire   [7:0] shl_ln1118_s_fu_2168_p3;
wire  signed [13:0] sext_ln1118_fu_2164_p1;
wire  signed [13:0] sext_ln1118_1_fu_2176_p1;
wire   [13:0] sub_ln1118_fu_2180_p2;
wire   [11:0] tmp_477_fu_2186_p4;
wire  signed [6:0] sext_ln1116_fu_2200_p0;
wire  signed [6:0] shl_ln1118_1_fu_2205_p1;
wire   [12:0] shl_ln1118_1_fu_2205_p3;
wire  signed [6:0] shl_ln1118_2_fu_2217_p1;
wire   [7:0] shl_ln1118_2_fu_2217_p3;
wire  signed [13:0] sext_ln1118_3_fu_2225_p1;
wire  signed [13:0] sext_ln1118_2_fu_2213_p1;
wire   [13:0] sub_ln1118_1_fu_2229_p2;
wire   [11:0] trunc_ln708_s_fu_2235_p4;
wire  signed [6:0] shl_ln1118_3_fu_2249_p1;
wire   [11:0] shl_ln1118_3_fu_2249_p3;
wire  signed [6:0] shl_ln1118_4_fu_2261_p1;
wire   [8:0] shl_ln1118_4_fu_2261_p3;
wire  signed [12:0] sext_ln1118_5_fu_2269_p1;
wire  signed [12:0] sext_ln1118_4_fu_2257_p1;
wire   [12:0] sub_ln1118_2_fu_2273_p2;
wire   [10:0] tmp_478_fu_2279_p4;
wire   [13:0] mul_ln1118_fu_291_p2;
wire   [11:0] trunc_ln708_114_fu_2293_p4;
wire  signed [6:0] sext_ln1116_1_fu_2307_p0;
wire  signed [6:0] shl_ln1118_5_fu_2312_p1;
wire   [12:0] shl_ln1118_5_fu_2312_p3;
wire  signed [6:0] shl_ln1118_6_fu_2324_p1;
wire  signed [7:0] shl_ln1118_6_fu_2324_p3;
wire  signed [13:0] sext_ln1118_6_fu_2320_p1;
wire  signed [13:0] sext_ln1118_8_fu_2336_p1;
wire   [13:0] sub_ln1118_3_fu_2340_p2;
wire   [11:0] trunc_ln708_115_fu_2346_p4;
wire  signed [6:0] shl_ln1118_7_fu_2360_p1;
wire   [10:0] shl_ln1118_7_fu_2360_p3;
wire  signed [11:0] sext_ln1118_7_fu_2332_p1;
wire  signed [11:0] sext_ln1118_9_fu_2368_p1;
wire   [11:0] sub_ln1118_4_fu_2372_p2;
wire   [9:0] tmp_479_fu_2378_p4;
wire   [13:0] mul_ln1118_1_fu_303_p2;
wire   [11:0] trunc_ln708_116_fu_2392_p4;
wire   [12:0] shl_ln1118_8_fu_2406_p3;
wire   [9:0] shl_ln1118_9_fu_2418_p3;
wire  signed [13:0] sext_ln1118_10_fu_2414_p1;
wire  signed [13:0] sext_ln1118_11_fu_2426_p1;
wire   [13:0] sub_ln1118_5_fu_2430_p2;
wire   [11:0] trunc_ln708_117_fu_2436_p4;
wire   [12:0] shl_ln1118_10_fu_2450_p3;
wire   [10:0] shl_ln1118_11_fu_2462_p3;
wire  signed [13:0] sext_ln1118_13_fu_2470_p1;
wire  signed [13:0] sext_ln1118_12_fu_2458_p1;
wire   [13:0] sub_ln1118_6_fu_2474_p2;
wire   [11:0] trunc_ln708_118_fu_2480_p4;
wire  signed [6:0] sext_ln1116_2_fu_2494_p0;
wire  signed [6:0] shl_ln1118_12_fu_2499_p1;
wire   [12:0] shl_ln1118_12_fu_2499_p3;
wire  signed [6:0] shl_ln1118_13_fu_2511_p1;
wire  signed [7:0] shl_ln1118_13_fu_2511_p3;
wire  signed [13:0] sext_ln1118_14_fu_2507_p1;
wire  signed [13:0] sext_ln1118_16_fu_2523_p1;
wire   [13:0] sub_ln1118_7_fu_2527_p2;
wire   [11:0] trunc_ln708_119_fu_2533_p4;
wire  signed [6:0] shl_ln1118_14_fu_2547_p1;
wire   [11:0] shl_ln1118_14_fu_2547_p3;
wire  signed [12:0] sext_ln1118_15_fu_2519_p1;
wire  signed [12:0] sext_ln1118_17_fu_2555_p1;
wire   [12:0] sub_ln1118_8_fu_2559_p2;
wire   [10:0] trunc_ln708_120_fu_2565_p4;
wire   [13:0] mul_ln1118_2_fu_285_p2;
wire   [11:0] trunc_ln708_121_fu_2579_p4;
wire   [13:0] mul_ln1118_3_fu_283_p2;
wire   [11:0] trunc_ln708_122_fu_2598_p4;
wire   [12:0] shl_ln1118_15_fu_2612_p3;
wire   [8:0] shl_ln1118_16_fu_2624_p3;
wire  signed [13:0] sext_ln1118_18_fu_2620_p1;
wire  signed [13:0] sext_ln1118_19_fu_2632_p1;
wire   [13:0] sub_ln1118_9_fu_2636_p2;
wire   [11:0] trunc_ln708_123_fu_2642_p4;
wire   [12:0] shl_ln1118_17_fu_2656_p3;
wire  signed [7:0] shl_ln1118_18_fu_2668_p3;
wire  signed [13:0] sext_ln1118_20_fu_2664_p1;
wire  signed [13:0] sext_ln1118_22_fu_2680_p1;
wire   [13:0] sub_ln1118_10_fu_2684_p2;
wire   [11:0] trunc_ln708_124_fu_2690_p4;
wire   [9:0] shl_ln1118_19_fu_2704_p3;
wire  signed [10:0] sext_ln1118_21_fu_2676_p1;
wire  signed [10:0] sext_ln1118_23_fu_2712_p1;
wire   [10:0] sub_ln1118_11_fu_2716_p2;
wire   [8:0] trunc_ln708_125_fu_2722_p4;
wire   [12:0] shl_ln1118_20_fu_2736_p3;
wire  signed [13:0] sext_ln1118_24_fu_2744_p1;
wire   [13:0] sub_ln1118_12_fu_2748_p2;
wire   [11:0] trunc_ln708_126_fu_2754_p4;
wire   [12:0] shl_ln1118_21_fu_2768_p3;
wire  signed [13:0] sext_ln1118_25_fu_2776_p1;
wire   [13:0] sub_ln1118_13_fu_2780_p2;
wire   [11:0] trunc_ln708_127_fu_2786_p4;
wire   [12:0] shl_ln1118_22_fu_2800_p3;
wire   [9:0] shl_ln1118_23_fu_2812_p3;
wire  signed [13:0] sext_ln1118_26_fu_2808_p1;
wire  signed [13:0] sext_ln1118_27_fu_2820_p1;
wire   [13:0] sub_ln1118_14_fu_2824_p2;
wire   [11:0] trunc_ln708_128_fu_2830_p4;
wire   [12:0] shl_ln1118_24_fu_2844_p3;
wire   [7:0] shl_ln1118_25_fu_2856_p3;
wire  signed [13:0] sext_ln1118_28_fu_2852_p1;
wire  signed [13:0] sext_ln1118_29_fu_2864_p1;
wire   [13:0] sub_ln1118_15_fu_2868_p2;
wire   [11:0] trunc_ln708_129_fu_2874_p4;
wire  signed [6:0] sext_ln1116_5_fu_2888_p0;
wire   [13:0] mul_ln1118_4_fu_310_p2;
wire   [11:0] trunc_ln708_130_fu_2894_p4;
wire   [13:0] mul_ln1118_5_fu_315_p2;
wire   [11:0] trunc_ln708_131_fu_2908_p4;
wire  signed [6:0] shl_ln1118_26_fu_2922_p1;
wire   [12:0] shl_ln1118_26_fu_2922_p3;
wire  signed [6:0] shl_ln1118_27_fu_2934_p1;
wire   [8:0] shl_ln1118_27_fu_2934_p3;
wire  signed [13:0] sext_ln1118_33_fu_2942_p1;
wire  signed [13:0] sext_ln1118_32_fu_2930_p1;
wire   [13:0] sub_ln1118_16_fu_2946_p2;
wire   [11:0] trunc_ln708_132_fu_2952_p4;
wire   [12:0] shl_ln1118_28_fu_2966_p3;
wire  signed [13:0] sext_ln1118_34_fu_2974_p1;
wire   [13:0] sub_ln1118_17_fu_2978_p2;
wire   [11:0] trunc_ln708_133_fu_2984_p4;
wire   [7:0] shl_ln1118_29_fu_2998_p3;
wire  signed [13:0] sext_ln1118_36_fu_3006_p1;
wire   [13:0] sub_ln1118_18_fu_3010_p2;
wire   [11:0] trunc_ln708_134_fu_3016_p4;
wire   [12:0] shl_ln1118_30_fu_3030_p3;
wire   [7:0] shl_ln1118_31_fu_3042_p3;
wire  signed [13:0] sext_ln1118_37_fu_3038_p1;
wire  signed [13:0] sext_ln1118_38_fu_3050_p1;
wire   [13:0] sub_ln1118_19_fu_3054_p2;
wire   [11:0] trunc_ln708_135_fu_3060_p4;
wire   [12:0] shl_ln1118_32_fu_3074_p3;
wire   [7:0] shl_ln1118_33_fu_3086_p3;
wire  signed [13:0] sext_ln1118_39_fu_3082_p1;
wire  signed [13:0] sext_ln1118_40_fu_3094_p1;
wire   [13:0] sub_ln1118_20_fu_3098_p2;
wire   [11:0] trunc_ln708_136_fu_3104_p4;
wire   [12:0] shl_ln1118_34_fu_3118_p3;
wire  signed [13:0] sext_ln1118_41_fu_3126_p1;
wire   [13:0] sub_ln1118_21_fu_3130_p2;
wire   [11:0] trunc_ln708_137_fu_3136_p4;
wire   [12:0] shl_ln1118_35_fu_3150_p3;
wire  signed [13:0] sext_ln1118_42_fu_3158_p1;
wire   [13:0] sub_ln1118_22_fu_3162_p2;
wire   [11:0] trunc_ln708_138_fu_3168_p4;
wire   [7:0] shl_ln1118_36_fu_3182_p3;
wire  signed [13:0] sext_ln1118_44_fu_3190_p1;
wire   [13:0] sub_ln1118_23_fu_3194_p2;
wire   [11:0] trunc_ln708_139_fu_3200_p4;
wire  signed [6:0] sext_ln1116_12_fu_3214_p0;
wire   [13:0] mul_ln1118_6_fu_313_p2;
wire   [11:0] trunc_ln708_140_fu_3219_p4;
wire  signed [6:0] shl_ln1118_37_fu_3233_p1;
wire   [12:0] shl_ln1118_37_fu_3233_p3;
wire  signed [6:0] shl_ln1118_38_fu_3245_p1;
wire   [7:0] shl_ln1118_38_fu_3245_p3;
wire  signed [13:0] sext_ln1118_47_fu_3253_p1;
wire  signed [13:0] sext_ln1118_46_fu_3241_p1;
wire   [13:0] sub_ln1118_24_fu_3257_p2;
wire   [11:0] trunc_ln708_141_fu_3263_p4;
wire   [12:0] shl_ln1118_39_fu_3277_p3;
wire  signed [13:0] sext_ln1118_48_fu_3285_p1;
wire   [13:0] sub_ln1118_25_fu_3289_p2;
wire   [11:0] trunc_ln708_142_fu_3295_p4;
wire  signed [6:0] sext_ln1116_15_fu_3309_p0;
wire   [13:0] mul_ln1118_7_fu_311_p2;
wire   [11:0] trunc_ln708_143_fu_3315_p4;
wire   [13:0] mul_ln1118_8_fu_278_p2;
wire   [11:0] trunc_ln708_144_fu_3329_p4;
wire  signed [6:0] shl_ln1118_40_fu_3343_p1;
wire   [12:0] shl_ln1118_40_fu_3343_p3;
wire  signed [6:0] shl_ln1118_41_fu_3355_p1;
wire   [7:0] shl_ln1118_41_fu_3355_p3;
wire  signed [13:0] sext_ln1118_51_fu_3351_p1;
wire  signed [13:0] sext_ln1118_52_fu_3363_p1;
wire   [13:0] sub_ln1118_26_fu_3367_p2;
wire   [11:0] tmp_480_fu_3373_p4;
wire  signed [6:0] sext_ln1116_17_fu_3387_p0;
wire   [13:0] mul_ln1118_9_fu_296_p2;
wire   [11:0] trunc_ln708_145_fu_3393_p4;
wire   [13:0] mul_ln1118_10_fu_284_p2;
wire   [11:0] trunc_ln708_146_fu_3407_p4;
wire  signed [6:0] shl_ln1118_42_fu_3421_p1;
wire   [11:0] shl_ln1118_42_fu_3421_p3;
wire  signed [6:0] shl_ln1118_43_fu_3433_p1;
wire   [8:0] shl_ln1118_43_fu_3433_p3;
wire  signed [12:0] sext_ln1118_56_fu_3441_p1;
wire  signed [12:0] sext_ln1118_55_fu_3429_p1;
wire   [12:0] add_ln1118_fu_3445_p2;
wire   [10:0] tmp_481_fu_3451_p4;
wire  signed [12:0] sext_ln203_fu_2245_p1;
wire  signed [12:0] sext_ln203_2_fu_2356_p1;
wire   [12:0] add_ln703_fu_3465_p2;
wire  signed [12:0] sext_ln203_6_fu_2543_p1;
wire  signed [12:0] sext_ln203_11_fu_2700_p1;
wire   [12:0] add_ln703_4_fu_3475_p2;
wire  signed [13:0] sext_ln703_2_fu_3481_p1;
wire  signed [13:0] sext_ln703_1_fu_3471_p1;
wire   [13:0] add_ln703_5_fu_3485_p2;
wire  signed [12:0] sext_ln203_13_fu_2764_p1;
wire  signed [12:0] sext_ln1118_30_fu_2904_p1;
wire   [12:0] add_ln703_6_fu_3495_p2;
wire  signed [12:0] sext_ln1118_49_fu_3325_p1;
wire   [12:0] add_ln703_7_fu_3505_p2;
wire  signed [13:0] sext_ln703_5_fu_3511_p1;
wire  signed [13:0] sext_ln1118_45_fu_3229_p1;
wire   [13:0] add_ln703_8_fu_3515_p2;
wire  signed [14:0] sext_ln703_6_fu_3521_p1;
wire  signed [14:0] sext_ln703_4_fu_3501_p1;
wire   [14:0] add_ln703_9_fu_3525_p2;
wire  signed [15:0] sext_ln703_7_fu_3531_p1;
wire  signed [15:0] sext_ln703_3_fu_3491_p1;
wire  signed [12:0] sext_ln1118_31_fu_2918_p1;
wire   [12:0] add_ln703_11_fu_3541_p2;
wire  signed [13:0] sext_ln703_8_fu_3547_p1;
wire  signed [13:0] sext_ln203_9_fu_2608_p1;
wire   [13:0] add_ln703_12_fu_3551_p2;
wire  signed [12:0] sext_ln1116_13_fu_3273_p1;
wire  signed [12:0] sext_ln1118_50_fu_3339_p1;
wire   [12:0] add_ln703_13_fu_3561_p2;
wire  signed [12:0] sext_ln1118_53_fu_3403_p1;
wire   [12:0] add_ln703_14_fu_3571_p2;
wire  signed [13:0] sext_ln703_11_fu_3577_p1;
wire  signed [13:0] sext_ln703_10_fu_3567_p1;
wire   [13:0] add_ln703_15_fu_3581_p2;
wire  signed [14:0] sext_ln703_12_fu_3587_p1;
wire  signed [14:0] sext_ln703_9_fu_3557_p1;
wire   [14:0] acc_1_V_fu_3591_p2;
wire  signed [11:0] sext_ln1118_57_fu_2289_p1;
wire  signed [11:0] sext_ln1118_58_fu_2388_p1;
wire   [11:0] add_ln703_17_fu_3601_p2;
wire  signed [12:0] sext_ln703_14_fu_3607_p1;
wire  signed [12:0] sext_ln1116_16_fu_2196_p1;
wire   [12:0] add_ln703_18_fu_3611_p2;
wire  signed [12:0] sext_ln203_7_fu_2575_p1;
wire  signed [12:0] sext_ln203_10_fu_2652_p1;
wire   [12:0] add_ln703_19_fu_3621_p2;
wire  signed [13:0] sext_ln703_16_fu_3627_p1;
wire  signed [13:0] sext_ln203_5_fu_2490_p1;
wire   [13:0] add_ln703_20_fu_3631_p2;
wire  signed [14:0] sext_ln703_17_fu_3637_p1;
wire  signed [14:0] sext_ln703_15_fu_3617_p1;
wire   [14:0] add_ln703_21_fu_3641_p2;
wire  signed [12:0] sext_ln203_14_fu_2796_p1;
wire  signed [12:0] sext_ln1116_4_fu_2884_p1;
wire   [12:0] add_ln703_22_fu_3651_p2;
wire  signed [13:0] sext_ln703_19_fu_3657_p1;
wire  signed [13:0] sext_ln203_12_fu_2732_p1;
wire   [13:0] add_ln703_23_fu_3661_p2;
wire  signed [12:0] sext_ln1116_10_fu_3146_p1;
wire  signed [12:0] sext_ln1118_43_fu_3178_p1;
wire   [12:0] add_ln703_24_fu_3671_p2;
wire  signed [12:0] sext_ln1118_54_fu_3417_p1;
wire   [12:0] add_ln703_25_fu_3681_p2;
wire  signed [13:0] sext_ln703_22_fu_3687_p1;
wire  signed [13:0] sext_ln703_21_fu_3677_p1;
wire   [13:0] add_ln703_26_fu_3691_p2;
wire  signed [14:0] sext_ln703_23_fu_3697_p1;
wire  signed [14:0] sext_ln703_20_fu_3667_p1;
wire   [14:0] add_ln703_27_fu_3701_p2;
wire  signed [15:0] sext_ln703_24_fu_3707_p1;
wire  signed [15:0] sext_ln703_18_fu_3647_p1;
wire  signed [12:0] sext_ln203_1_fu_2303_p1;
wire  signed [12:0] sext_ln203_3_fu_2402_p1;
wire   [12:0] add_ln703_29_fu_3717_p2;
wire  signed [12:0] sext_ln203_8_fu_2589_p1;
wire  signed [12:0] sext_ln203_15_fu_2840_p1;
wire   [12:0] add_ln703_30_fu_3727_p2;
wire  signed [13:0] sext_ln703_26_fu_3733_p1;
wire  signed [13:0] sext_ln203_4_fu_2446_p1;
wire   [13:0] add_ln703_31_fu_3737_p2;
wire  signed [14:0] sext_ln703_27_fu_3743_p1;
wire  signed [14:0] sext_ln703_25_fu_3723_p1;
wire   [14:0] add_ln703_32_fu_3747_p2;
wire  signed [12:0] sext_ln1118_35_fu_2994_p1;
wire  signed [12:0] sext_ln1116_8_fu_3070_p1;
wire   [12:0] add_ln703_33_fu_3757_p2;
wire  signed [13:0] sext_ln703_29_fu_3763_p1;
wire  signed [13:0] sext_ln1116_6_fu_2962_p1;
wire   [13:0] add_ln703_34_fu_3767_p2;
wire  signed [12:0] sext_ln1116_14_fu_3305_p1;
wire   [12:0] add_ln703_35_fu_3777_p2;
wire  signed [13:0] sext_ln703_31_fu_3783_p1;
wire  signed [13:0] sext_ln1116_9_fu_3114_p1;
wire   [13:0] add_ln703_36_fu_3787_p2;
wire  signed [14:0] sext_ln703_32_fu_3793_p1;
wire  signed [14:0] sext_ln703_30_fu_3773_p1;
wire   [14:0] add_ln703_37_fu_3797_p2;
wire  signed [15:0] sext_ln703_33_fu_3803_p1;
wire  signed [15:0] sext_ln703_28_fu_3753_p1;
wire  signed [12:0] sext_ln1116_7_fu_3026_p1;
wire  signed [12:0] sext_ln1116_11_fu_3210_p1;
wire   [12:0] add_ln703_39_fu_3813_p2;
wire  signed [11:0] sext_ln703_fu_3461_p1;
wire   [11:0] add_ln703_40_fu_3823_p2;
wire  signed [12:0] sext_ln703_35_fu_3829_p1;
wire  signed [12:0] sext_ln1116_18_fu_3383_p1;
wire   [12:0] add_ln703_41_fu_3833_p2;
wire  signed [13:0] sext_ln703_36_fu_3839_p1;
wire  signed [13:0] sext_ln703_34_fu_3819_p1;
wire   [13:0] acc_4_V_fu_3843_p2;
wire   [15:0] add_ln703_10_fu_3535_p2;
wire  signed [15:0] sext_ln703_13_fu_3597_p1;
wire   [15:0] acc_2_V_fu_3711_p2;
wire   [15:0] acc_3_V_fu_3807_p2;
wire  signed [15:0] sext_ln703_37_fu_3849_p1;

assign acc_1_V_fu_3591_p2 = ($signed(sext_ln703_12_fu_3587_p1) + $signed(sext_ln703_9_fu_3557_p1));

assign acc_2_V_fu_3711_p2 = ($signed(sext_ln703_24_fu_3707_p1) + $signed(sext_ln703_18_fu_3647_p1));

assign acc_3_V_fu_3807_p2 = ($signed(sext_ln703_33_fu_3803_p1) + $signed(sext_ln703_28_fu_3753_p1));

assign acc_4_V_fu_3843_p2 = ($signed(sext_ln703_36_fu_3839_p1) + $signed(sext_ln703_34_fu_3819_p1));

assign add_ln1118_fu_3445_p2 = ($signed(sext_ln1118_56_fu_3441_p1) + $signed(sext_ln1118_55_fu_3429_p1));

assign add_ln703_10_fu_3535_p2 = ($signed(sext_ln703_7_fu_3531_p1) + $signed(sext_ln703_3_fu_3491_p1));

assign add_ln703_11_fu_3541_p2 = ($signed(sext_ln203_13_fu_2764_p1) + $signed(sext_ln1118_31_fu_2918_p1));

assign add_ln703_12_fu_3551_p2 = ($signed(sext_ln703_8_fu_3547_p1) + $signed(sext_ln203_9_fu_2608_p1));

assign add_ln703_13_fu_3561_p2 = ($signed(sext_ln1116_13_fu_3273_p1) + $signed(sext_ln1118_50_fu_3339_p1));

assign add_ln703_14_fu_3571_p2 = ($signed(sext_ln1118_53_fu_3403_p1) + $signed(13'd192));

assign add_ln703_15_fu_3581_p2 = ($signed(sext_ln703_11_fu_3577_p1) + $signed(sext_ln703_10_fu_3567_p1));

assign add_ln703_17_fu_3601_p2 = ($signed(sext_ln1118_57_fu_2289_p1) + $signed(sext_ln1118_58_fu_2388_p1));

assign add_ln703_18_fu_3611_p2 = ($signed(sext_ln703_14_fu_3607_p1) + $signed(sext_ln1116_16_fu_2196_p1));

assign add_ln703_19_fu_3621_p2 = ($signed(sext_ln203_7_fu_2575_p1) + $signed(sext_ln203_10_fu_2652_p1));

assign add_ln703_20_fu_3631_p2 = ($signed(sext_ln703_16_fu_3627_p1) + $signed(sext_ln203_5_fu_2490_p1));

assign add_ln703_21_fu_3641_p2 = ($signed(sext_ln703_17_fu_3637_p1) + $signed(sext_ln703_15_fu_3617_p1));

assign add_ln703_22_fu_3651_p2 = ($signed(sext_ln203_14_fu_2796_p1) + $signed(sext_ln1116_4_fu_2884_p1));

assign add_ln703_23_fu_3661_p2 = ($signed(sext_ln703_19_fu_3657_p1) + $signed(sext_ln203_12_fu_2732_p1));

assign add_ln703_24_fu_3671_p2 = ($signed(sext_ln1116_10_fu_3146_p1) + $signed(sext_ln1118_43_fu_3178_p1));

assign add_ln703_25_fu_3681_p2 = ($signed(sext_ln1118_54_fu_3417_p1) + $signed(13'd544));

assign add_ln703_26_fu_3691_p2 = ($signed(sext_ln703_22_fu_3687_p1) + $signed(sext_ln703_21_fu_3677_p1));

assign add_ln703_27_fu_3701_p2 = ($signed(sext_ln703_23_fu_3697_p1) + $signed(sext_ln703_20_fu_3667_p1));

assign add_ln703_29_fu_3717_p2 = ($signed(sext_ln203_1_fu_2303_p1) + $signed(sext_ln203_3_fu_2402_p1));

assign add_ln703_30_fu_3727_p2 = ($signed(sext_ln203_8_fu_2589_p1) + $signed(sext_ln203_15_fu_2840_p1));

assign add_ln703_31_fu_3737_p2 = ($signed(sext_ln703_26_fu_3733_p1) + $signed(sext_ln203_4_fu_2446_p1));

assign add_ln703_32_fu_3747_p2 = ($signed(sext_ln703_27_fu_3743_p1) + $signed(sext_ln703_25_fu_3723_p1));

assign add_ln703_33_fu_3757_p2 = ($signed(sext_ln1118_35_fu_2994_p1) + $signed(sext_ln1116_8_fu_3070_p1));

assign add_ln703_34_fu_3767_p2 = ($signed(sext_ln703_29_fu_3763_p1) + $signed(sext_ln1116_6_fu_2962_p1));

assign add_ln703_35_fu_3777_p2 = ($signed(sext_ln1116_14_fu_3305_p1) + $signed(13'd7872));

assign add_ln703_36_fu_3787_p2 = ($signed(sext_ln703_31_fu_3783_p1) + $signed(sext_ln1116_9_fu_3114_p1));

assign add_ln703_37_fu_3797_p2 = ($signed(sext_ln703_32_fu_3793_p1) + $signed(sext_ln703_30_fu_3773_p1));

assign add_ln703_39_fu_3813_p2 = ($signed(sext_ln1116_7_fu_3026_p1) + $signed(sext_ln1116_11_fu_3210_p1));

assign add_ln703_40_fu_3823_p2 = ($signed(sext_ln703_fu_3461_p1) + $signed(12'd3456));

assign add_ln703_41_fu_3833_p2 = ($signed(sext_ln703_35_fu_3829_p1) + $signed(sext_ln1116_18_fu_3383_p1));

assign add_ln703_4_fu_3475_p2 = ($signed(sext_ln203_6_fu_2543_p1) + $signed(sext_ln203_11_fu_2700_p1));

assign add_ln703_5_fu_3485_p2 = ($signed(sext_ln703_2_fu_3481_p1) + $signed(sext_ln703_1_fu_3471_p1));

assign add_ln703_6_fu_3495_p2 = ($signed(sext_ln203_13_fu_2764_p1) + $signed(sext_ln1118_30_fu_2904_p1));

assign add_ln703_7_fu_3505_p2 = ($signed(sext_ln1118_49_fu_3325_p1) + $signed(13'd352));

assign add_ln703_8_fu_3515_p2 = ($signed(sext_ln703_5_fu_3511_p1) + $signed(sext_ln1118_45_fu_3229_p1));

assign add_ln703_9_fu_3525_p2 = ($signed(sext_ln703_6_fu_3521_p1) + $signed(sext_ln703_4_fu_3501_p1));

assign add_ln703_fu_3465_p2 = ($signed(sext_ln203_fu_2245_p1) + $signed(sext_ln203_2_fu_2356_p1));

assign ap_ready = 1'b1;

assign ap_return_0 = add_ln703_10_fu_3535_p2;

assign ap_return_1 = sext_ln703_13_fu_3597_p1;

assign ap_return_2 = acc_2_V_fu_3711_p2;

assign ap_return_3 = acc_3_V_fu_3807_p2;

assign ap_return_4 = sext_ln703_37_fu_3849_p1;

assign mul_ln1118_10_fu_284_p0 = sext_ln1116_17_fu_3387_p1;

assign mul_ln1118_10_fu_284_p2 = ($signed(mul_ln1118_10_fu_284_p0) * $signed('h36));

assign mul_ln1118_1_fu_303_p0 = sext_ln1116_1_fu_2307_p0;

assign mul_ln1118_1_fu_303_p2 = ($signed(mul_ln1118_1_fu_303_p0) * $signed(-'h2A));

assign mul_ln1118_2_fu_285_p0 = sext_ln1116_2_fu_2494_p0;

assign mul_ln1118_2_fu_285_p2 = ($signed(mul_ln1118_2_fu_285_p0) * $signed(-'h2A));

assign mul_ln1118_3_fu_283_p0 = data_8_V_read;

assign mul_ln1118_3_fu_283_p2 = ($signed(mul_ln1118_3_fu_283_p0) * $signed('h3A));

assign mul_ln1118_4_fu_310_p0 = sext_ln1116_5_fu_2888_p1;

assign mul_ln1118_4_fu_310_p2 = ($signed(mul_ln1118_4_fu_310_p0) * $signed(-'h34));

assign mul_ln1118_5_fu_315_p0 = sext_ln1116_5_fu_2888_p1;

assign mul_ln1118_5_fu_315_p2 = ($signed(mul_ln1118_5_fu_315_p0) * $signed('h3A));

assign mul_ln1118_6_fu_313_p0 = sext_ln1116_12_fu_3214_p0;

assign mul_ln1118_6_fu_313_p2 = ($signed(mul_ln1118_6_fu_313_p0) * $signed(-'h3A));

assign mul_ln1118_7_fu_311_p0 = sext_ln1116_15_fu_3309_p1;

assign mul_ln1118_7_fu_311_p2 = ($signed(mul_ln1118_7_fu_311_p0) * $signed(-'h2C));

assign mul_ln1118_8_fu_278_p0 = sext_ln1116_15_fu_3309_p1;

assign mul_ln1118_8_fu_278_p2 = ($signed(mul_ln1118_8_fu_278_p0) * $signed(-'h32));

assign mul_ln1118_9_fu_296_p0 = sext_ln1116_17_fu_3387_p1;

assign mul_ln1118_9_fu_296_p2 = ($signed(mul_ln1118_9_fu_296_p0) * $signed(-'h32));

assign mul_ln1118_fu_291_p0 = sext_ln1116_fu_2200_p0;

assign mul_ln1118_fu_291_p2 = ($signed(mul_ln1118_fu_291_p0) * $signed('h32));

assign sext_ln1116_10_fu_3146_p1 = $signed(trunc_ln708_137_fu_3136_p4);

assign sext_ln1116_11_fu_3210_p1 = $signed(trunc_ln708_139_fu_3200_p4);

assign sext_ln1116_12_fu_3214_p0 = data_27_V_read;

assign sext_ln1116_13_fu_3273_p1 = $signed(trunc_ln708_141_fu_3263_p4);

assign sext_ln1116_14_fu_3305_p1 = $signed(trunc_ln708_142_fu_3295_p4);

assign sext_ln1116_15_fu_3309_p0 = data_29_V_read;

assign sext_ln1116_15_fu_3309_p1 = sext_ln1116_15_fu_3309_p0;

assign sext_ln1116_16_fu_2196_p1 = $signed(tmp_477_fu_2186_p4);

assign sext_ln1116_17_fu_3387_p0 = data_31_V_read;

assign sext_ln1116_17_fu_3387_p1 = sext_ln1116_17_fu_3387_p0;

assign sext_ln1116_18_fu_3383_p1 = $signed(tmp_480_fu_3373_p4);

assign sext_ln1116_1_fu_2307_p0 = data_3_V_read;

assign sext_ln1116_2_fu_2494_p0 = data_7_V_read;

assign sext_ln1116_4_fu_2884_p1 = $signed(trunc_ln708_129_fu_2874_p4);

assign sext_ln1116_5_fu_2888_p0 = data_19_V_read;

assign sext_ln1116_5_fu_2888_p1 = sext_ln1116_5_fu_2888_p0;

assign sext_ln1116_6_fu_2962_p1 = $signed(trunc_ln708_132_fu_2952_p4);

assign sext_ln1116_7_fu_3026_p1 = $signed(trunc_ln708_134_fu_3016_p4);

assign sext_ln1116_8_fu_3070_p1 = $signed(trunc_ln708_135_fu_3060_p4);

assign sext_ln1116_9_fu_3114_p1 = $signed(trunc_ln708_136_fu_3104_p4);

assign sext_ln1116_fu_2200_p0 = data_2_V_read;

assign sext_ln1118_10_fu_2414_p1 = $signed(shl_ln1118_8_fu_2406_p3);

assign sext_ln1118_11_fu_2426_p1 = $signed(shl_ln1118_9_fu_2418_p3);

assign sext_ln1118_12_fu_2458_p1 = $signed(shl_ln1118_10_fu_2450_p3);

assign sext_ln1118_13_fu_2470_p1 = $signed(shl_ln1118_11_fu_2462_p3);

assign sext_ln1118_14_fu_2507_p1 = $signed(shl_ln1118_12_fu_2499_p3);

assign sext_ln1118_15_fu_2519_p1 = shl_ln1118_13_fu_2511_p3;

assign sext_ln1118_16_fu_2523_p1 = shl_ln1118_13_fu_2511_p3;

assign sext_ln1118_17_fu_2555_p1 = $signed(shl_ln1118_14_fu_2547_p3);

assign sext_ln1118_18_fu_2620_p1 = $signed(shl_ln1118_15_fu_2612_p3);

assign sext_ln1118_19_fu_2632_p1 = $signed(shl_ln1118_16_fu_2624_p3);

assign sext_ln1118_1_fu_2176_p1 = $signed(shl_ln1118_s_fu_2168_p3);

assign sext_ln1118_20_fu_2664_p1 = $signed(shl_ln1118_17_fu_2656_p3);

assign sext_ln1118_21_fu_2676_p1 = shl_ln1118_18_fu_2668_p3;

assign sext_ln1118_22_fu_2680_p1 = shl_ln1118_18_fu_2668_p3;

assign sext_ln1118_23_fu_2712_p1 = $signed(shl_ln1118_19_fu_2704_p3);

assign sext_ln1118_24_fu_2744_p1 = $signed(shl_ln1118_20_fu_2736_p3);

assign sext_ln1118_25_fu_2776_p1 = $signed(shl_ln1118_21_fu_2768_p3);

assign sext_ln1118_26_fu_2808_p1 = $signed(shl_ln1118_22_fu_2800_p3);

assign sext_ln1118_27_fu_2820_p1 = $signed(shl_ln1118_23_fu_2812_p3);

assign sext_ln1118_28_fu_2852_p1 = $signed(shl_ln1118_24_fu_2844_p3);

assign sext_ln1118_29_fu_2864_p1 = $signed(shl_ln1118_25_fu_2856_p3);

assign sext_ln1118_2_fu_2213_p1 = $signed(shl_ln1118_1_fu_2205_p3);

assign sext_ln1118_30_fu_2904_p1 = $signed(trunc_ln708_130_fu_2894_p4);

assign sext_ln1118_31_fu_2918_p1 = $signed(trunc_ln708_131_fu_2908_p4);

assign sext_ln1118_32_fu_2930_p1 = $signed(shl_ln1118_26_fu_2922_p3);

assign sext_ln1118_33_fu_2942_p1 = $signed(shl_ln1118_27_fu_2934_p3);

assign sext_ln1118_34_fu_2974_p1 = $signed(shl_ln1118_28_fu_2966_p3);

assign sext_ln1118_35_fu_2994_p1 = $signed(trunc_ln708_133_fu_2984_p4);

assign sext_ln1118_36_fu_3006_p1 = $signed(shl_ln1118_29_fu_2998_p3);

assign sext_ln1118_37_fu_3038_p1 = $signed(shl_ln1118_30_fu_3030_p3);

assign sext_ln1118_38_fu_3050_p1 = $signed(shl_ln1118_31_fu_3042_p3);

assign sext_ln1118_39_fu_3082_p1 = $signed(shl_ln1118_32_fu_3074_p3);

assign sext_ln1118_3_fu_2225_p1 = $signed(shl_ln1118_2_fu_2217_p3);

assign sext_ln1118_40_fu_3094_p1 = $signed(shl_ln1118_33_fu_3086_p3);

assign sext_ln1118_41_fu_3126_p1 = $signed(shl_ln1118_34_fu_3118_p3);

assign sext_ln1118_42_fu_3158_p1 = $signed(shl_ln1118_35_fu_3150_p3);

assign sext_ln1118_43_fu_3178_p1 = $signed(trunc_ln708_138_fu_3168_p4);

assign sext_ln1118_44_fu_3190_p1 = $signed(shl_ln1118_36_fu_3182_p3);

assign sext_ln1118_45_fu_3229_p1 = $signed(trunc_ln708_140_fu_3219_p4);

assign sext_ln1118_46_fu_3241_p1 = $signed(shl_ln1118_37_fu_3233_p3);

assign sext_ln1118_47_fu_3253_p1 = $signed(shl_ln1118_38_fu_3245_p3);

assign sext_ln1118_48_fu_3285_p1 = $signed(shl_ln1118_39_fu_3277_p3);

assign sext_ln1118_49_fu_3325_p1 = $signed(trunc_ln708_143_fu_3315_p4);

assign sext_ln1118_4_fu_2257_p1 = $signed(shl_ln1118_3_fu_2249_p3);

assign sext_ln1118_50_fu_3339_p1 = $signed(trunc_ln708_144_fu_3329_p4);

assign sext_ln1118_51_fu_3351_p1 = $signed(shl_ln1118_40_fu_3343_p3);

assign sext_ln1118_52_fu_3363_p1 = $signed(shl_ln1118_41_fu_3355_p3);

assign sext_ln1118_53_fu_3403_p1 = $signed(trunc_ln708_145_fu_3393_p4);

assign sext_ln1118_54_fu_3417_p1 = $signed(trunc_ln708_146_fu_3407_p4);

assign sext_ln1118_55_fu_3429_p1 = $signed(shl_ln1118_42_fu_3421_p3);

assign sext_ln1118_56_fu_3441_p1 = $signed(shl_ln1118_43_fu_3433_p3);

assign sext_ln1118_57_fu_2289_p1 = $signed(tmp_478_fu_2279_p4);

assign sext_ln1118_58_fu_2388_p1 = $signed(tmp_479_fu_2378_p4);

assign sext_ln1118_5_fu_2269_p1 = $signed(shl_ln1118_4_fu_2261_p3);

assign sext_ln1118_6_fu_2320_p1 = $signed(shl_ln1118_5_fu_2312_p3);

assign sext_ln1118_7_fu_2332_p1 = shl_ln1118_6_fu_2324_p3;

assign sext_ln1118_8_fu_2336_p1 = shl_ln1118_6_fu_2324_p3;

assign sext_ln1118_9_fu_2368_p1 = $signed(shl_ln1118_7_fu_2360_p3);

assign sext_ln1118_fu_2164_p1 = $signed(shl_ln_fu_2156_p3);

assign sext_ln203_10_fu_2652_p1 = $signed(trunc_ln708_123_fu_2642_p4);

assign sext_ln203_11_fu_2700_p1 = $signed(trunc_ln708_124_fu_2690_p4);

assign sext_ln203_12_fu_2732_p1 = $signed(trunc_ln708_125_fu_2722_p4);

assign sext_ln203_13_fu_2764_p1 = $signed(trunc_ln708_126_fu_2754_p4);

assign sext_ln203_14_fu_2796_p1 = $signed(trunc_ln708_127_fu_2786_p4);

assign sext_ln203_15_fu_2840_p1 = $signed(trunc_ln708_128_fu_2830_p4);

assign sext_ln203_1_fu_2303_p1 = $signed(trunc_ln708_114_fu_2293_p4);

assign sext_ln203_2_fu_2356_p1 = $signed(trunc_ln708_115_fu_2346_p4);

assign sext_ln203_3_fu_2402_p1 = $signed(trunc_ln708_116_fu_2392_p4);

assign sext_ln203_4_fu_2446_p1 = $signed(trunc_ln708_117_fu_2436_p4);

assign sext_ln203_5_fu_2490_p1 = $signed(trunc_ln708_118_fu_2480_p4);

assign sext_ln203_6_fu_2543_p1 = $signed(trunc_ln708_119_fu_2533_p4);

assign sext_ln203_7_fu_2575_p1 = $signed(trunc_ln708_120_fu_2565_p4);

assign sext_ln203_8_fu_2589_p1 = $signed(trunc_ln708_121_fu_2579_p4);

assign sext_ln203_9_fu_2608_p1 = $signed(trunc_ln708_122_fu_2598_p4);

assign sext_ln203_fu_2245_p1 = $signed(trunc_ln708_s_fu_2235_p4);

assign sext_ln703_10_fu_3567_p1 = $signed(add_ln703_13_fu_3561_p2);

assign sext_ln703_11_fu_3577_p1 = $signed(add_ln703_14_fu_3571_p2);

assign sext_ln703_12_fu_3587_p1 = $signed(add_ln703_15_fu_3581_p2);

assign sext_ln703_13_fu_3597_p1 = $signed(acc_1_V_fu_3591_p2);

assign sext_ln703_14_fu_3607_p1 = $signed(add_ln703_17_fu_3601_p2);

assign sext_ln703_15_fu_3617_p1 = $signed(add_ln703_18_fu_3611_p2);

assign sext_ln703_16_fu_3627_p1 = $signed(add_ln703_19_fu_3621_p2);

assign sext_ln703_17_fu_3637_p1 = $signed(add_ln703_20_fu_3631_p2);

assign sext_ln703_18_fu_3647_p1 = $signed(add_ln703_21_fu_3641_p2);

assign sext_ln703_19_fu_3657_p1 = $signed(add_ln703_22_fu_3651_p2);

assign sext_ln703_1_fu_3471_p1 = $signed(add_ln703_fu_3465_p2);

assign sext_ln703_20_fu_3667_p1 = $signed(add_ln703_23_fu_3661_p2);

assign sext_ln703_21_fu_3677_p1 = $signed(add_ln703_24_fu_3671_p2);

assign sext_ln703_22_fu_3687_p1 = $signed(add_ln703_25_fu_3681_p2);

assign sext_ln703_23_fu_3697_p1 = $signed(add_ln703_26_fu_3691_p2);

assign sext_ln703_24_fu_3707_p1 = $signed(add_ln703_27_fu_3701_p2);

assign sext_ln703_25_fu_3723_p1 = $signed(add_ln703_29_fu_3717_p2);

assign sext_ln703_26_fu_3733_p1 = $signed(add_ln703_30_fu_3727_p2);

assign sext_ln703_27_fu_3743_p1 = $signed(add_ln703_31_fu_3737_p2);

assign sext_ln703_28_fu_3753_p1 = $signed(add_ln703_32_fu_3747_p2);

assign sext_ln703_29_fu_3763_p1 = $signed(add_ln703_33_fu_3757_p2);

assign sext_ln703_2_fu_3481_p1 = $signed(add_ln703_4_fu_3475_p2);

assign sext_ln703_30_fu_3773_p1 = $signed(add_ln703_34_fu_3767_p2);

assign sext_ln703_31_fu_3783_p1 = $signed(add_ln703_35_fu_3777_p2);

assign sext_ln703_32_fu_3793_p1 = $signed(add_ln703_36_fu_3787_p2);

assign sext_ln703_33_fu_3803_p1 = $signed(add_ln703_37_fu_3797_p2);

assign sext_ln703_34_fu_3819_p1 = $signed(add_ln703_39_fu_3813_p2);

assign sext_ln703_35_fu_3829_p1 = $signed(add_ln703_40_fu_3823_p2);

assign sext_ln703_36_fu_3839_p1 = $signed(add_ln703_41_fu_3833_p2);

assign sext_ln703_37_fu_3849_p1 = $signed(acc_4_V_fu_3843_p2);

assign sext_ln703_3_fu_3491_p1 = $signed(add_ln703_5_fu_3485_p2);

assign sext_ln703_4_fu_3501_p1 = $signed(add_ln703_6_fu_3495_p2);

assign sext_ln703_5_fu_3511_p1 = $signed(add_ln703_7_fu_3505_p2);

assign sext_ln703_6_fu_3521_p1 = $signed(add_ln703_8_fu_3515_p2);

assign sext_ln703_7_fu_3531_p1 = $signed(add_ln703_9_fu_3525_p2);

assign sext_ln703_8_fu_3547_p1 = $signed(add_ln703_11_fu_3541_p2);

assign sext_ln703_9_fu_3557_p1 = $signed(add_ln703_12_fu_3551_p2);

assign sext_ln703_fu_3461_p1 = $signed(tmp_481_fu_3451_p4);

assign shl_ln1118_10_fu_2450_p3 = {{data_6_V_read}, {6'd0}};

assign shl_ln1118_11_fu_2462_p3 = {{data_6_V_read}, {4'd0}};

assign shl_ln1118_12_fu_2499_p1 = data_7_V_read;

assign shl_ln1118_12_fu_2499_p3 = {{shl_ln1118_12_fu_2499_p1}, {6'd0}};

assign shl_ln1118_13_fu_2511_p1 = data_7_V_read;

assign shl_ln1118_13_fu_2511_p3 = {{shl_ln1118_13_fu_2511_p1}, {1'd0}};

assign shl_ln1118_14_fu_2547_p1 = data_7_V_read;

assign shl_ln1118_14_fu_2547_p3 = {{shl_ln1118_14_fu_2547_p1}, {5'd0}};

assign shl_ln1118_15_fu_2612_p3 = {{data_9_V_read}, {6'd0}};

assign shl_ln1118_16_fu_2624_p3 = {{data_9_V_read}, {2'd0}};

assign shl_ln1118_17_fu_2656_p3 = {{data_10_V_read}, {6'd0}};

assign shl_ln1118_18_fu_2668_p3 = {{data_10_V_read}, {1'd0}};

assign shl_ln1118_19_fu_2704_p3 = {{data_10_V_read}, {3'd0}};

assign shl_ln1118_1_fu_2205_p1 = data_2_V_read;

assign shl_ln1118_1_fu_2205_p3 = {{shl_ln1118_1_fu_2205_p1}, {6'd0}};

assign shl_ln1118_20_fu_2736_p3 = {{data_12_V_read}, {6'd0}};

assign shl_ln1118_21_fu_2768_p3 = {{data_14_V_read}, {6'd0}};

assign shl_ln1118_22_fu_2800_p3 = {{data_15_V_read}, {6'd0}};

assign shl_ln1118_23_fu_2812_p3 = {{data_15_V_read}, {3'd0}};

assign shl_ln1118_24_fu_2844_p3 = {{data_17_V_read}, {6'd0}};

assign shl_ln1118_25_fu_2856_p3 = {{data_17_V_read}, {1'd0}};

assign shl_ln1118_26_fu_2922_p1 = data_19_V_read;

assign shl_ln1118_26_fu_2922_p3 = {{shl_ln1118_26_fu_2922_p1}, {6'd0}};

assign shl_ln1118_27_fu_2934_p1 = data_19_V_read;

assign shl_ln1118_27_fu_2934_p3 = {{shl_ln1118_27_fu_2934_p1}, {2'd0}};

assign shl_ln1118_28_fu_2966_p3 = {{data_20_V_read}, {6'd0}};

assign shl_ln1118_29_fu_2998_p3 = {{data_20_V_read}, {1'd0}};

assign shl_ln1118_2_fu_2217_p1 = data_2_V_read;

assign shl_ln1118_2_fu_2217_p3 = {{shl_ln1118_2_fu_2217_p1}, {1'd0}};

assign shl_ln1118_30_fu_3030_p3 = {{data_21_V_read}, {6'd0}};

assign shl_ln1118_31_fu_3042_p3 = {{data_21_V_read}, {1'd0}};

assign shl_ln1118_32_fu_3074_p3 = {{data_24_V_read}, {6'd0}};

assign shl_ln1118_33_fu_3086_p3 = {{data_24_V_read}, {1'd0}};

assign shl_ln1118_34_fu_3118_p3 = {{data_25_V_read}, {6'd0}};

assign shl_ln1118_35_fu_3150_p3 = {{data_26_V_read}, {6'd0}};

assign shl_ln1118_36_fu_3182_p3 = {{data_26_V_read}, {1'd0}};

assign shl_ln1118_37_fu_3233_p1 = data_27_V_read;

assign shl_ln1118_37_fu_3233_p3 = {{shl_ln1118_37_fu_3233_p1}, {6'd0}};

assign shl_ln1118_38_fu_3245_p1 = data_27_V_read;

assign shl_ln1118_38_fu_3245_p3 = {{shl_ln1118_38_fu_3245_p1}, {1'd0}};

assign shl_ln1118_39_fu_3277_p3 = {{data_28_V_read}, {6'd0}};

assign shl_ln1118_3_fu_2249_p1 = data_2_V_read;

assign shl_ln1118_3_fu_2249_p3 = {{shl_ln1118_3_fu_2249_p1}, {5'd0}};

assign shl_ln1118_40_fu_3343_p1 = data_29_V_read;

assign shl_ln1118_40_fu_3343_p3 = {{shl_ln1118_40_fu_3343_p1}, {6'd0}};

assign shl_ln1118_41_fu_3355_p1 = data_29_V_read;

assign shl_ln1118_41_fu_3355_p3 = {{shl_ln1118_41_fu_3355_p1}, {1'd0}};

assign shl_ln1118_42_fu_3421_p1 = data_31_V_read;

assign shl_ln1118_42_fu_3421_p3 = {{shl_ln1118_42_fu_3421_p1}, {5'd0}};

assign shl_ln1118_43_fu_3433_p1 = data_31_V_read;

assign shl_ln1118_43_fu_3433_p3 = {{shl_ln1118_43_fu_3433_p1}, {2'd0}};

assign shl_ln1118_4_fu_2261_p1 = data_2_V_read;

assign shl_ln1118_4_fu_2261_p3 = {{shl_ln1118_4_fu_2261_p1}, {2'd0}};

assign shl_ln1118_5_fu_2312_p1 = data_3_V_read;

assign shl_ln1118_5_fu_2312_p3 = {{shl_ln1118_5_fu_2312_p1}, {6'd0}};

assign shl_ln1118_6_fu_2324_p1 = data_3_V_read;

assign shl_ln1118_6_fu_2324_p3 = {{shl_ln1118_6_fu_2324_p1}, {1'd0}};

assign shl_ln1118_7_fu_2360_p1 = data_3_V_read;

assign shl_ln1118_7_fu_2360_p3 = {{shl_ln1118_7_fu_2360_p1}, {4'd0}};

assign shl_ln1118_8_fu_2406_p3 = {{data_5_V_read}, {6'd0}};

assign shl_ln1118_9_fu_2418_p3 = {{data_5_V_read}, {3'd0}};

assign shl_ln1118_s_fu_2168_p3 = {{data_0_V_read}, {1'd0}};

assign shl_ln_fu_2156_p3 = {{data_0_V_read}, {6'd0}};

assign sub_ln1118_10_fu_2684_p2 = ($signed(sext_ln1118_20_fu_2664_p1) - $signed(sext_ln1118_22_fu_2680_p1));

assign sub_ln1118_11_fu_2716_p2 = ($signed(sext_ln1118_21_fu_2676_p1) - $signed(sext_ln1118_23_fu_2712_p1));

assign sub_ln1118_12_fu_2748_p2 = ($signed(14'd0) - $signed(sext_ln1118_24_fu_2744_p1));

assign sub_ln1118_13_fu_2780_p2 = ($signed(14'd0) - $signed(sext_ln1118_25_fu_2776_p1));

assign sub_ln1118_14_fu_2824_p2 = ($signed(sext_ln1118_26_fu_2808_p1) - $signed(sext_ln1118_27_fu_2820_p1));

assign sub_ln1118_15_fu_2868_p2 = ($signed(sext_ln1118_28_fu_2852_p1) - $signed(sext_ln1118_29_fu_2864_p1));

assign sub_ln1118_16_fu_2946_p2 = ($signed(sext_ln1118_33_fu_2942_p1) - $signed(sext_ln1118_32_fu_2930_p1));

assign sub_ln1118_17_fu_2978_p2 = ($signed(14'd0) - $signed(sext_ln1118_34_fu_2974_p1));

assign sub_ln1118_18_fu_3010_p2 = ($signed(sext_ln1118_34_fu_2974_p1) - $signed(sext_ln1118_36_fu_3006_p1));

assign sub_ln1118_19_fu_3054_p2 = ($signed(sext_ln1118_37_fu_3038_p1) - $signed(sext_ln1118_38_fu_3050_p1));

assign sub_ln1118_1_fu_2229_p2 = ($signed(sext_ln1118_3_fu_2225_p1) - $signed(sext_ln1118_2_fu_2213_p1));

assign sub_ln1118_20_fu_3098_p2 = ($signed(sext_ln1118_39_fu_3082_p1) - $signed(sext_ln1118_40_fu_3094_p1));

assign sub_ln1118_21_fu_3130_p2 = ($signed(14'd0) - $signed(sext_ln1118_41_fu_3126_p1));

assign sub_ln1118_22_fu_3162_p2 = ($signed(14'd0) - $signed(sext_ln1118_42_fu_3158_p1));

assign sub_ln1118_23_fu_3194_p2 = ($signed(sext_ln1118_42_fu_3158_p1) - $signed(sext_ln1118_44_fu_3190_p1));

assign sub_ln1118_24_fu_3257_p2 = ($signed(sext_ln1118_47_fu_3253_p1) - $signed(sext_ln1118_46_fu_3241_p1));

assign sub_ln1118_25_fu_3289_p2 = ($signed(14'd0) - $signed(sext_ln1118_48_fu_3285_p1));

assign sub_ln1118_26_fu_3367_p2 = ($signed(sext_ln1118_51_fu_3351_p1) - $signed(sext_ln1118_52_fu_3363_p1));

assign sub_ln1118_2_fu_2273_p2 = ($signed(sext_ln1118_5_fu_2269_p1) - $signed(sext_ln1118_4_fu_2257_p1));

assign sub_ln1118_3_fu_2340_p2 = ($signed(sext_ln1118_6_fu_2320_p1) - $signed(sext_ln1118_8_fu_2336_p1));

assign sub_ln1118_4_fu_2372_p2 = ($signed(sext_ln1118_7_fu_2332_p1) - $signed(sext_ln1118_9_fu_2368_p1));

assign sub_ln1118_5_fu_2430_p2 = ($signed(sext_ln1118_10_fu_2414_p1) - $signed(sext_ln1118_11_fu_2426_p1));

assign sub_ln1118_6_fu_2474_p2 = ($signed(sext_ln1118_13_fu_2470_p1) - $signed(sext_ln1118_12_fu_2458_p1));

assign sub_ln1118_7_fu_2527_p2 = ($signed(sext_ln1118_14_fu_2507_p1) - $signed(sext_ln1118_16_fu_2523_p1));

assign sub_ln1118_8_fu_2559_p2 = ($signed(sext_ln1118_15_fu_2519_p1) - $signed(sext_ln1118_17_fu_2555_p1));

assign sub_ln1118_9_fu_2636_p2 = ($signed(sext_ln1118_18_fu_2620_p1) - $signed(sext_ln1118_19_fu_2632_p1));

assign sub_ln1118_fu_2180_p2 = ($signed(sext_ln1118_fu_2164_p1) - $signed(sext_ln1118_1_fu_2176_p1));

assign tmp_477_fu_2186_p4 = {{sub_ln1118_fu_2180_p2[13:2]}};

assign tmp_478_fu_2279_p4 = {{sub_ln1118_2_fu_2273_p2[12:2]}};

assign tmp_479_fu_2378_p4 = {{sub_ln1118_4_fu_2372_p2[11:2]}};

assign tmp_480_fu_3373_p4 = {{sub_ln1118_26_fu_3367_p2[13:2]}};

assign tmp_481_fu_3451_p4 = {{add_ln1118_fu_3445_p2[12:2]}};

assign trunc_ln708_114_fu_2293_p4 = {{mul_ln1118_fu_291_p2[13:2]}};

assign trunc_ln708_115_fu_2346_p4 = {{sub_ln1118_3_fu_2340_p2[13:2]}};

assign trunc_ln708_116_fu_2392_p4 = {{mul_ln1118_1_fu_303_p2[13:2]}};

assign trunc_ln708_117_fu_2436_p4 = {{sub_ln1118_5_fu_2430_p2[13:2]}};

assign trunc_ln708_118_fu_2480_p4 = {{sub_ln1118_6_fu_2474_p2[13:2]}};

assign trunc_ln708_119_fu_2533_p4 = {{sub_ln1118_7_fu_2527_p2[13:2]}};

assign trunc_ln708_120_fu_2565_p4 = {{sub_ln1118_8_fu_2559_p2[12:2]}};

assign trunc_ln708_121_fu_2579_p4 = {{mul_ln1118_2_fu_285_p2[13:2]}};

assign trunc_ln708_122_fu_2598_p4 = {{mul_ln1118_3_fu_283_p2[13:2]}};

assign trunc_ln708_123_fu_2642_p4 = {{sub_ln1118_9_fu_2636_p2[13:2]}};

assign trunc_ln708_124_fu_2690_p4 = {{sub_ln1118_10_fu_2684_p2[13:2]}};

assign trunc_ln708_125_fu_2722_p4 = {{sub_ln1118_11_fu_2716_p2[10:2]}};

assign trunc_ln708_126_fu_2754_p4 = {{sub_ln1118_12_fu_2748_p2[13:2]}};

assign trunc_ln708_127_fu_2786_p4 = {{sub_ln1118_13_fu_2780_p2[13:2]}};

assign trunc_ln708_128_fu_2830_p4 = {{sub_ln1118_14_fu_2824_p2[13:2]}};

assign trunc_ln708_129_fu_2874_p4 = {{sub_ln1118_15_fu_2868_p2[13:2]}};

assign trunc_ln708_130_fu_2894_p4 = {{mul_ln1118_4_fu_310_p2[13:2]}};

assign trunc_ln708_131_fu_2908_p4 = {{mul_ln1118_5_fu_315_p2[13:2]}};

assign trunc_ln708_132_fu_2952_p4 = {{sub_ln1118_16_fu_2946_p2[13:2]}};

assign trunc_ln708_133_fu_2984_p4 = {{sub_ln1118_17_fu_2978_p2[13:2]}};

assign trunc_ln708_134_fu_3016_p4 = {{sub_ln1118_18_fu_3010_p2[13:2]}};

assign trunc_ln708_135_fu_3060_p4 = {{sub_ln1118_19_fu_3054_p2[13:2]}};

assign trunc_ln708_136_fu_3104_p4 = {{sub_ln1118_20_fu_3098_p2[13:2]}};

assign trunc_ln708_137_fu_3136_p4 = {{sub_ln1118_21_fu_3130_p2[13:2]}};

assign trunc_ln708_138_fu_3168_p4 = {{sub_ln1118_22_fu_3162_p2[13:2]}};

assign trunc_ln708_139_fu_3200_p4 = {{sub_ln1118_23_fu_3194_p2[13:2]}};

assign trunc_ln708_140_fu_3219_p4 = {{mul_ln1118_6_fu_313_p2[13:2]}};

assign trunc_ln708_141_fu_3263_p4 = {{sub_ln1118_24_fu_3257_p2[13:2]}};

assign trunc_ln708_142_fu_3295_p4 = {{sub_ln1118_25_fu_3289_p2[13:2]}};

assign trunc_ln708_143_fu_3315_p4 = {{mul_ln1118_7_fu_311_p2[13:2]}};

assign trunc_ln708_144_fu_3329_p4 = {{mul_ln1118_8_fu_278_p2[13:2]}};

assign trunc_ln708_145_fu_3393_p4 = {{mul_ln1118_9_fu_296_p2[13:2]}};

assign trunc_ln708_146_fu_3407_p4 = {{mul_ln1118_10_fu_284_p2[13:2]}};

assign trunc_ln708_s_fu_2235_p4 = {{sub_ln1118_1_fu_2229_p2[13:2]}};

endmodule //dense_latency_ap_fixed_ap_fixed_config11_0_0_0_0_0_0
